In [1]:
import numpy as np

In [2]:
x = np.array([1, 2, 3, 4, 5])

result = x ** 2

print("x:", x)
print("x squared:", result)

x: [1 2 3 4 5]
x squared: [ 1  4  9 16 25]


In [3]:
y = 2 * x + 5

print("y = 2x + 5:", y)

y = 2x + 5: [ 7  9 11 13 15]


1. What is vectorization?

Vectorization is the process of performing an operation on an entire NumPy array without explicitly writing a Python loop for each element.

2. Why is vectorization useful?

Vectorization makes code shorter, clearer, easier to maintain, and generally faster, especially when processing large datasets.

3. Difference between a Python loop and a NumPy vectorized operation?

A Python loop processes elements one at a time using explicit iteration, while a NumPy vectorized operation performs the operation on the entire array using optimized numerical operations.

In [4]:
marks = np.array([40, 55, 62, 70, 81, 90])

print("Original marks:", marks)

Original marks: [40 55 62 70 81 90]


In [5]:
adjusted = marks + 5

print("Adjusted marks:", adjusted)

Adjusted marks: [45 60 67 75 86 95]


In [6]:
percentage = marks / 100

print("Percentage:", percentage)

Percentage: [0.4  0.55 0.62 0.7  0.81 0.9 ]


In [7]:
z = (marks - np.mean(marks)) / np.std(marks)

print("Standardized values:", z)
print("Mean of z:", np.mean(z))

Standardized values: [-1.59799895 -0.68774638 -0.26296185  0.22250618  0.89002473  1.43617627]
Mean of z: 2.590520390792032e-16


In [8]:
data = np.array([
    [60, 70, 80],
    [50, 65, 75],
    [90, 85, 95]
])

adjustment = np.array([5, 0, 2])

print("Data:")
print(data)

print("Adjustment:")
print(adjustment)

Data:
[[60 70 80]
 [50 65 75]
 [90 85 95]]
Adjustment:
[5 0 2]


In [9]:
result = data + adjustment

print("Result:")
print(result)

Result:
[[65 70 82]
 [55 65 77]
 [95 85 97]]


Broadcasting allows NumPy to perform operations between arrays with compatible shapes. In this example, the 1 × 3 adjustment array is automatically applied to each row of the 3 × 3 data array. NumPy does this without explicitly copying the adjustment array.

In [10]:
data = np.array([
    [10, 20, 30],
    [20, 30, 40],
    [30, 40, 50]
])

print("Data:")
print(data)

Data:
[[10 20 30]
 [20 30 40]
 [30 40 50]]


In [11]:
means = data.mean(axis=0)

print("Column means:", means)

Column means: [20. 30. 40.]


In [12]:
centered = data - means

print("Centered data:")
print(centered)

Centered data:
[[-10. -10. -10.]
 [  0.   0.   0.]
 [ 10.  10.  10.]]


In [13]:
print("Mean of centered columns:", centered.mean(axis=0))

Mean of centered columns: [0. 0. 0.]


The vector of column means has shape (3,), while the data matrix has shape (3, 3). NumPy broadcasts the three means across the corresponding columns and subtracts each mean from every value in that column. Therefore, each centered column has a mean of approximately zero.

In [14]:
x = np.arange(1_000_000)

print("Number of values:", len(x))
print("First 10 values:", x[:10])

Number of values: 1000000
First 10 values: [0 1 2 3 4 5 6 7 8 9]


In [15]:
result_loop = []

for value in x:
    result_loop.append(value**2 + 2*value + 1)

print("First 10 loop results:", result_loop[:10])

First 10 loop results: [np.int64(1), np.int64(4), np.int64(9), np.int64(16), np.int64(25), np.int64(36), np.int64(49), np.int64(64), np.int64(81), np.int64(100)]


In [16]:
result_vectorized = x**2 + 2*x + 1

print("First 10 vectorized results:", result_vectorized[:10])

First 10 vectorized results: [  1   4   9  16  25  36  49  64  81 100]


In [17]:
print("Results equal:", np.allclose(result_loop, result_vectorized))

Results equal: True


1. Are the two results equal?

Yes. np.allclose() returns True, showing that the loop-based and vectorized results agree.

2. Which approach is easier to read?

The vectorized NumPy approach is generally easier to read because the mathematical operation is expressed directly without an explicit loop.

3. Which approach would you expect to be faster?

The NumPy vectorized approach would generally be faster for a large array.

4. Why?

NumPy performs vectorized operations using optimized numerical routines implemented largely in compiled code, reducing the overhead of executing a Python loop for each element.

In [20]:
np.random.seed(123)

x = np.random.normal(100, 15, 100_000)

print("Number of observations:", len(x))
print("First 10 observations:", x[:10])

Number of observations: 100000
First 10 observations: [ 83.71554095 114.9601817  104.24467747  77.40557929  91.32099622
 124.77154806  63.59981135  93.56631057 118.98904388  86.99889397]


In [21]:
z = (x - x.mean()) / x.std()

print("Mean of z:", z.mean())
print("Standard deviation of z:", z.std())

Mean of z: -9.839595804805867e-16
Standard deviation of z: 0.9999999999999999


Vectorization is particularly useful for large statistical datasets because it allows mathematical operations to be performed on many observations at once without explicitly writing Python loops. This results in shorter and clearer code and generally improves computational efficiency. In this example, 100,000 observations were standardized using a single vectorized expression.

In [22]:
def standardize(x):
    return (x - np.mean(x)) / np.std(x)

In [23]:
x1 = np.array([10, 20, 30, 40, 50])
x2 = np.array([5, 10, 15, 20, 25])
x3 = np.array([100, 150, 200, 250, 300])

z1 = standardize(x1)
z2 = standardize(x2)
z3 = standardize(x3)

print("Standardized x1:", z1)
print("Mean of x1:", np.mean(z1))
print()

print("Standardized x2:", z2)
print("Mean of x2:", np.mean(z2))
print()

print("Standardized x3:", z3)
print("Mean of x3:", np.mean(z3))

Standardized x1: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
Mean of x1: 0.0

Standardized x2: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
Mean of x2: 0.0

Standardized x3: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
Mean of x3: 0.0


In [24]:
def standardize_columns(x):
    return (x - np.mean(x, axis=0)) / np.std(x, axis=0)

In [25]:
data_2d = np.array([
    [10, 20, 30],
    [20, 30, 40],
    [30, 40, 50],
    [40, 50, 60]
])

standardized_data = standardize_columns(data_2d)

print("Original data:")
print(data_2d)

print("\nStandardized data:")
print(standardized_data)

print("\nColumn means:")
print(standardized_data.mean(axis=0))

print("\nColumn standard deviations:")
print(standardized_data.std(axis=0))

Original data:
[[10 20 30]
 [20 30 40]
 [30 40 50]
 [40 50 60]]

Standardized data:
[[-1.34164079 -1.34164079 -1.34164079]
 [-0.4472136  -0.4472136  -0.4472136 ]
 [ 0.4472136   0.4472136   0.4472136 ]
 [ 1.34164079  1.34164079  1.34164079]]

Column means:
[0. 0. 0.]

Column standard deviations:
[1. 1. 1.]


For a 2D dataset:
axis=0 calculates statistics down each column. Therefore, np.mean(x, axis=0) produces one mean for every column, while np.std(x, axis=0) produces one standard deviation for every column. NumPy then broadcasts these vectors across the rows, allowing every column to be standardized simultaneously.